services:
    _defaults:
        autowire: true
        public: false
        autoconfigure: true

    Uniplaces\RequestLoggerBundle\EventListener\RequestLoggerEventListener:
        tags:
            -
                name: kernel.event_listener
                event: kernel.response
                method: onResponse
