services:
    request_logger_bundle.request_logger:
        class: Uniplaces\RequestLoggerBundle\EventListener\RequestLoggerEventListener
        arguments: ["@logger"]
        tags:
            -
                name: kernel.event_listener
                event: kernel.request
                method: onRequest
            -
                name: kernel.event_listener
                event: kernel.terminate
                method: onTerminate
